server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://121.89.174.31:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

  redis:
    port: 6379
    host: 121.89.174.31
    password: 123456
    timeout: 3000
    # 连接池
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大空闲连接
        max-idle: 8
        # 最新空连接
        min-idle: 0
        # 阻塞时间
        max-wait: -1

#  邮件发送配置
  mail:
#    用户名
    username: cueyucueyu@163.com
#    授权码
    password: CGZDVZSUDISSEMHL
#    smtp服务器地址
    host: smtp.163.com
    default-encoding: UTF-8

logging:
  file:
    name: my.log
    path: ./
    max-history: 1
    max-size: 10MB
  level:
    root: info

mybatis:
#  type-aliases-package: com.syclover.geekPlatform.entity
  mapper-locations: classpath:mappers/*.xml

